# Netlify Configuration for TIPN Community Leaderboard

[build]
  # Vite build process
  publish = "dist"
  command = "npm run build"

# Redirect root to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=3600"
    
    # CORS for API calls
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Special headers for Farcaster Mini App manifest
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=86400"

# Longer cache for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  [context.production.environment]
    NODE_ENV = "production"
    ENVIRONMENT = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    ENVIRONMENT = "preview"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    ENVIRONMENT = "branch"

# Form handling (if needed later for contact/feedback)
[forms]
  settings = true

# Functions directory (if adding Netlify Functions later)
[functions]
  directory = "netlify/functions"